name: CICD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Install Specific Dependencies
        run: npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Build React Project
        run: npm run build
        env:
          CI: false

      - name: Build Docker Image
        run: docker build -t aj4941/spell_checker_frontend:latest .

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push aj4941/spell_checker_frontend:latest

      - name: SSH into AWS EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 43.200.252.131
          debug: true
          port: 22
          username: ubuntu
          key: ${{ secrets.SECRET_KEY }}
          script: |
            '/home/ubuntu/deploy-frontend.sh'
